services:
  client:
    build:
      context: .
      dockerfile: ./Dockerfile-Dev
    command: ["npm", "run", "client:dev"]
    depends_on:
      - server
    environment:
      - BASE_URL=http://localhost:3000
      - SESSION_SECRET_KEY=$SESSION_SECRET_KEY
      - SESSION_SECRET_IV=$SESSION_SECRET_IV
    networks:
      - habitica
    volumes:
      - .:/usr/src/habitica
  server:
    build:
      context: .
      dockerfile: ./Dockerfile-Dev
    command: ["npm", "start"]
    depends_on:
      mongo:
        condition: service_healthy
    environment:
      - NODE_DB_URI=mongodb://mongo/habitrpg
      - SESSION_SECRET_KEY=$SESSION_SECRET_KEY
      - SESSION_SECRET_IV=$SESSION_SECRET_IV
      - PAYPAL_MODE=sandbox
    networks:
      - habitica
    volumes:
      - .:/usr/src/habitica
  mongo:
    image: mongo:5.0.23
    restart: unless-stopped
    command: ["--replSet", "rs", "--bind_ip_all", "--port", "27017"]
    healthcheck:
      test: echo "try { rs.status() } catch (err) { rs.initiate() }" | mongosh --port 27017 --quiet
      interval: 10s
      timeout: 30s
      start_period: 0s
      start_interval: 1s
      retries: 30
    networks:
      - habitica
    ports:
      - 27017
networks:
  habitica:
    driver: bridge
