FROM node:20
ARG BASE_URL
ENV BASE_URL=${BASE_URL}

# Global packages
RUN npm install -g gulp-cli mocha

# Root
WORKDIR /usr/src/habitica
COPY package*.json ./
COPY . .
RUN npm install                   # Install root deps for server
WORKDIR /usr/src/habitica/website/client
RUN npm install                   # Install client deps for Vite etc
WORKDIR /usr/src/habitica         # Go back to root

RUN npm run postinstall
RUN npm run client:build
RUN gulp build:prod
