FROM node:20
ARG BASE_URL
ENV BASE_URL=${BASE_URL}

# Global packages
RUN npm install -g gulp-cli mocha

# Root
WORKDIR /usr/src/habitica
COPY ["package.json", "package-lock.json", "./"]
COPY . /usr/src/habitica

RUN npm install

# install client deps BEFORE building client
WORKDIR /usr/src/habitica/website/client
RUN npm install

# Go back to root to continue
WORKDIR /usr/src/habitica

RUN npm run postinstall
RUN npm run client:build
RUN gulp build:prod
