FROM node:20
ARG BASE_URL
ENV BASE_URL=${BASE_URL}

RUN npm install -g gulp-cli mocha

WORKDIR /usr/src/habitica
COPY package*.json ./
COPY . .
RUN npm install

WORKDIR /usr/src/habitica/website/client
RUN npm install

WORKDIR /usr/src/habitica

RUN npm run postinstall
RUN npm run client:build
RUN gulp build:prod
